USE [master];
GO

IF NOT EXISTS (SELECT name FROM sys.server_principals WHERE name = '<SQL_MONITOR_USER>')
BEGIN
    CREATE LOGIN [<SQL_MONITOR_USER>]
    WITH PASSWORD = N'<SQL_MONITOR_PASSWORD>',
    CHECK_EXPIRATION = OFF,
    CHECK_POLICY = OFF;
END;
GO

USE [msdb];
GO

IF EXISTS (SELECT name FROM sys.database_principals WHERE name = '<SQL_MONITOR_USER>')
BEGIN
    DROP USER [<SQL_MONITOR_USER>];
END;
GO

CREATE USER [<SQL_MONITOR_USER>] FOR LOGIN [<SQL_MONITOR_USER>];
GO

ALTER ROLE [SQLAgentReaderRole] ADD MEMBER [<SQL_MONITOR_USER>];
GO

GRANT SELECT ON [dbo].[sysjobs] TO [<SQL_MONITOR_USER>];
GRANT SELECT ON [dbo].[sysjobhistory] TO [<SQL_MONITOR_USER>];
GRANT SELECT ON [dbo].[sysjobsteps] TO [<SQL_MONITOR_USER>];
GO
